### ISSUE TITLE
Crash on xCode 8.3

### ISSUE THREAD

**Issue by TsvetelinVladimirov** [STAR-ZERO/XFunnyEditor#3]
After xCode 8.3 update the plugin crashes xCode on selecting the plugin options menu and select background.

**Comment by STAR-ZERO** [comment]
Please re-install and restart.

**Comment by TsvetelinVladimirov** [comment]
This doesn't solve the problem! Removed the plugin from via Alcatraz -> removed it manually from the plug-in directory -> restarted xCode, installed the plugin via Alcatraz -> restarted xCode -> and still crashes

**Comment by STAR-ZERO** [comment]
Remove the directory and file of the following, and re-install from Alcatraz
* `~/Library/Application Support/Alcatraz/Plug-ins/XFunnyEditor``
* `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin`
