### ISSUE TITLE
When I check [ScaleFit] and uncheck [ScaleFit],it become from [centerInside] to [center]

### ISSUE THREAD

**Issue by dyguests** [STAR-ZERO/XFunnyEditor#5]
thanks for you job.It;s GREAT!

however,when I check [ScaleFit] and uncheck [ScaleFit],it become from [centerInside] to [center].
so,there is 3 types??

by the way,i like [center].

**Comment by STAR-ZERO** [comment]
Thanks, fixed. 36f5b1c4f27fafda33d071d37b6dfc8f92032b8e

Sorry, [center] yet not support. I want to add an option someday.
